### ISSUE TITLE
Use modified time instead of time

### ISSUE THREAD

**Issue by Zodiac1978** [glueckpress/aged-content-message#7]
If you have outdated content this message is a great feature. But if you manually update your old content I want the message to disappear.

So maybe we could use use  [get_the_modified_time](https://codex.wordpress.org/Function_Reference/get_the_modified_time) instead of [get_the_time](https://github.com/glueckpress/aged-content-message/blob/master/inc/frontend.php#L26)

But only if the modified time is different to the published time. Something like this: 
`if (get_the_modified_time() != get_the_time())` for using `get_the_modified_time`

I can provide a PR if I have some spare time.

**Comment by glueckpress** [comment]
See https://github.com/glueckpress/aged-content-message/pull/8

**Comment by Zodiac1978** [comment]
Nice! :)
I tested it and it works like a charm. But I think it is an edge case. Because you can't edit and save a post now without removing the message. Maybe this was a nice idea in theory but not for real world usage. An per-page-solution would be an overkill ...

**Comment by glueckpress** [comment]
Closing this because I’m not continuing with the plugin.
